//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 06:53:36 PM IST 
//


package com.bbby.eom.service.order.cancel.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PickLocAssignmentType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BackorderQty" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="9"/&gt;
 *                   &lt;fractionDigits value="2"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CubeMultipleQty" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="4"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UnitWeight" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="4"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UnitVolume" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="4"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LPNBrkAttribute" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CriticalDimension1" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="7"/&gt;
 *                   &lt;fractionDigits value="2"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CriticalDimension2" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="7"/&gt;
 *                   &lt;fractionDigits value="2"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CriticalDimension3" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="7"/&gt;
 *                   &lt;fractionDigits value="2"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="VASProcessType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Price" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="9"/&gt;
 *                   &lt;fractionDigits value="2"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomTag" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PackRate" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="9"/&gt;
 *                   &lt;fractionDigits value="4"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SerialNbrReq" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value=""/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartialFill" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SingleUnit" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Y"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value=""/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BatchReqmtType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TpePOSeq" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PriceTicketType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ExportIdCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="FI"/&gt;
 *               &lt;enumeration value="FS"/&gt;
 *               &lt;enumeration value="OI"/&gt;
 *               &lt;enumeration value="OS"/&gt;
 *               &lt;enumeration value="CH"/&gt;
 *               &lt;enumeration value="CI"/&gt;
 *               &lt;enumeration value="IP"/&gt;
 *               &lt;enumeration value="IR"/&gt;
 *               &lt;enumeration value="TP"/&gt;
 *               &lt;enumeration value="ZD"/&gt;
 *               &lt;enumeration value=""/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WaveProcessingType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                   &lt;totalDigits value="3"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ChuteAssignType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ItemBreakAttribute" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="15"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="InventoryAllocationType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PickupReferenceNbr" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DeliveryReferenceNbr" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField1" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField2" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField3" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField4" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField5" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField6" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField7" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField8" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField9" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefTextField10" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="25"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefNumberField1" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="5"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefNumberField2" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="5"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefNumberField3" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="5"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefNumberField4" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="5"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LineRefNumberField5" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                   &lt;totalDigits value="13"/&gt;
 *                   &lt;fractionDigits value="5"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;enumeration value=""/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pickLocAssignmentType",
    "backorderQty",
    "cubeMultipleQty",
    "unitWeight",
    "unitVolume",
    "lpnBrkAttribute",
    "criticalDimension1",
    "criticalDimension2",
    "criticalDimension3",
    "vasProcessType",
    "price",
    "customTag",
    "packRate",
    "serialNbrReq",
    "partialFill",
    "singleUnit",
    "batchReqmtType",
    "tpePOSeq",
    "priceTicketType",
    "exportIdCode",
    "waveProcessingType",
    "chuteAssignType",
    "itemBreakAttribute",
    "inventoryAllocationType",
    "pickupReferenceNbr",
    "deliveryReferenceNbr",
    "lineRefTextField1",
    "lineRefTextField2",
    "lineRefTextField3",
    "lineRefTextField4",
    "lineRefTextField5",
    "lineRefTextField6",
    "lineRefTextField7",
    "lineRefTextField8",
    "lineRefTextField9",
    "lineRefTextField10",
    "lineRefNumberField1",
    "lineRefNumberField2",
    "lineRefNumberField3",
    "lineRefNumberField4",
    "lineRefNumberField5"
})
public class LineWMProcessInfo {

    @XmlElementRef(name = "PickLocAssignmentType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pickLocAssignmentType;
    @XmlElementRef(name = "BackorderQty", type = JAXBElement.class, required = false)
    protected JAXBElement<String> backorderQty;
    @XmlElementRef(name = "CubeMultipleQty", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cubeMultipleQty;
    @XmlElementRef(name = "UnitWeight", type = JAXBElement.class, required = false)
    protected JAXBElement<String> unitWeight;
    @XmlElementRef(name = "UnitVolume", type = JAXBElement.class, required = false)
    protected JAXBElement<String> unitVolume;
    @XmlElementRef(name = "LPNBrkAttribute", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lpnBrkAttribute;
    @XmlElementRef(name = "CriticalDimension1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> criticalDimension1;
    @XmlElementRef(name = "CriticalDimension2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> criticalDimension2;
    @XmlElementRef(name = "CriticalDimension3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> criticalDimension3;
    @XmlElementRef(name = "VASProcessType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> vasProcessType;
    @XmlElementRef(name = "Price", type = JAXBElement.class, required = false)
    protected JAXBElement<String> price;
    @XmlElementRef(name = "CustomTag", type = JAXBElement.class, required = false)
    protected JAXBElement<String> customTag;
    @XmlElementRef(name = "PackRate", type = JAXBElement.class, required = false)
    protected JAXBElement<String> packRate;
    @XmlElementRef(name = "SerialNbrReq", type = JAXBElement.class, required = false)
    protected JAXBElement<String> serialNbrReq;
    @XmlElementRef(name = "PartialFill", type = JAXBElement.class, required = false)
    protected JAXBElement<String> partialFill;
    @XmlElementRef(name = "SingleUnit", type = JAXBElement.class, required = false)
    protected JAXBElement<String> singleUnit;
    @XmlElementRef(name = "BatchReqmtType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> batchReqmtType;
    @XmlElementRef(name = "TpePOSeq", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tpePOSeq;
    @XmlElementRef(name = "PriceTicketType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> priceTicketType;
    @XmlElementRef(name = "ExportIdCode", type = JAXBElement.class, required = false)
    protected JAXBElement<String> exportIdCode;
    @XmlElementRef(name = "WaveProcessingType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> waveProcessingType;
    @XmlElementRef(name = "ChuteAssignType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> chuteAssignType;
    @XmlElementRef(name = "ItemBreakAttribute", type = JAXBElement.class, required = false)
    protected JAXBElement<String> itemBreakAttribute;
    @XmlElementRef(name = "InventoryAllocationType", type = JAXBElement.class, required = false)
    protected JAXBElement<String> inventoryAllocationType;
    @XmlElementRef(name = "PickupReferenceNbr", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pickupReferenceNbr;
    @XmlElementRef(name = "DeliveryReferenceNbr", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deliveryReferenceNbr;
    @XmlElementRef(name = "LineRefTextField1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField1;
    @XmlElementRef(name = "LineRefTextField2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField2;
    @XmlElementRef(name = "LineRefTextField3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField3;
    @XmlElementRef(name = "LineRefTextField4", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField4;
    @XmlElementRef(name = "LineRefTextField5", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField5;
    @XmlElementRef(name = "LineRefTextField6", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField6;
    @XmlElementRef(name = "LineRefTextField7", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField7;
    @XmlElementRef(name = "LineRefTextField8", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField8;
    @XmlElementRef(name = "LineRefTextField9", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField9;
    @XmlElementRef(name = "LineRefTextField10", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField10;
    @XmlElementRef(name = "LineRefNumberField1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField1;
    @XmlElementRef(name = "LineRefNumberField2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField2;
    @XmlElementRef(name = "LineRefNumberField3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField3;
    @XmlElementRef(name = "LineRefNumberField4", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField4;
    @XmlElementRef(name = "LineRefNumberField5", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField5;

    /**
     * Gets the value of the pickLocAssignmentType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPickLocAssignmentType() {
        return pickLocAssignmentType;
    }

    /**
     * Sets the value of the pickLocAssignmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPickLocAssignmentType(JAXBElement<String> value) {
        this.pickLocAssignmentType = value;
    }

    /**
     * Gets the value of the backorderQty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBackorderQty() {
        return backorderQty;
    }

    /**
     * Sets the value of the backorderQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBackorderQty(JAXBElement<String> value) {
        this.backorderQty = value;
    }

    /**
     * Gets the value of the cubeMultipleQty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCubeMultipleQty() {
        return cubeMultipleQty;
    }

    /**
     * Sets the value of the cubeMultipleQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCubeMultipleQty(JAXBElement<String> value) {
        this.cubeMultipleQty = value;
    }

    /**
     * Gets the value of the unitWeight property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUnitWeight() {
        return unitWeight;
    }

    /**
     * Sets the value of the unitWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUnitWeight(JAXBElement<String> value) {
        this.unitWeight = value;
    }

    /**
     * Gets the value of the unitVolume property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUnitVolume() {
        return unitVolume;
    }

    /**
     * Sets the value of the unitVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUnitVolume(JAXBElement<String> value) {
        this.unitVolume = value;
    }

    /**
     * Gets the value of the lpnBrkAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLPNBrkAttribute() {
        return lpnBrkAttribute;
    }

    /**
     * Sets the value of the lpnBrkAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLPNBrkAttribute(JAXBElement<String> value) {
        this.lpnBrkAttribute = value;
    }

    /**
     * Gets the value of the criticalDimension1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCriticalDimension1() {
        return criticalDimension1;
    }

    /**
     * Sets the value of the criticalDimension1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCriticalDimension1(JAXBElement<String> value) {
        this.criticalDimension1 = value;
    }

    /**
     * Gets the value of the criticalDimension2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCriticalDimension2() {
        return criticalDimension2;
    }

    /**
     * Sets the value of the criticalDimension2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCriticalDimension2(JAXBElement<String> value) {
        this.criticalDimension2 = value;
    }

    /**
     * Gets the value of the criticalDimension3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCriticalDimension3() {
        return criticalDimension3;
    }

    /**
     * Sets the value of the criticalDimension3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCriticalDimension3(JAXBElement<String> value) {
        this.criticalDimension3 = value;
    }

    /**
     * Gets the value of the vasProcessType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getVASProcessType() {
        return vasProcessType;
    }

    /**
     * Sets the value of the vasProcessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setVASProcessType(JAXBElement<String> value) {
        this.vasProcessType = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPrice(JAXBElement<String> value) {
        this.price = value;
    }

    /**
     * Gets the value of the customTag property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCustomTag() {
        return customTag;
    }

    /**
     * Sets the value of the customTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCustomTag(JAXBElement<String> value) {
        this.customTag = value;
    }

    /**
     * Gets the value of the packRate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPackRate() {
        return packRate;
    }

    /**
     * Sets the value of the packRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPackRate(JAXBElement<String> value) {
        this.packRate = value;
    }

    /**
     * Gets the value of the serialNbrReq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSerialNbrReq() {
        return serialNbrReq;
    }

    /**
     * Sets the value of the serialNbrReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSerialNbrReq(JAXBElement<String> value) {
        this.serialNbrReq = value;
    }

    /**
     * Gets the value of the partialFill property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPartialFill() {
        return partialFill;
    }

    /**
     * Sets the value of the partialFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPartialFill(JAXBElement<String> value) {
        this.partialFill = value;
    }

    /**
     * Gets the value of the singleUnit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSingleUnit() {
        return singleUnit;
    }

    /**
     * Sets the value of the singleUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSingleUnit(JAXBElement<String> value) {
        this.singleUnit = value;
    }

    /**
     * Gets the value of the batchReqmtType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBatchReqmtType() {
        return batchReqmtType;
    }

    /**
     * Sets the value of the batchReqmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBatchReqmtType(JAXBElement<String> value) {
        this.batchReqmtType = value;
    }

    /**
     * Gets the value of the tpePOSeq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTpePOSeq() {
        return tpePOSeq;
    }

    /**
     * Sets the value of the tpePOSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTpePOSeq(JAXBElement<String> value) {
        this.tpePOSeq = value;
    }

    /**
     * Gets the value of the priceTicketType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPriceTicketType() {
        return priceTicketType;
    }

    /**
     * Sets the value of the priceTicketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPriceTicketType(JAXBElement<String> value) {
        this.priceTicketType = value;
    }

    /**
     * Gets the value of the exportIdCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExportIdCode() {
        return exportIdCode;
    }

    /**
     * Sets the value of the exportIdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExportIdCode(JAXBElement<String> value) {
        this.exportIdCode = value;
    }

    /**
     * Gets the value of the waveProcessingType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWaveProcessingType() {
        return waveProcessingType;
    }

    /**
     * Sets the value of the waveProcessingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWaveProcessingType(JAXBElement<String> value) {
        this.waveProcessingType = value;
    }

    /**
     * Gets the value of the chuteAssignType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getChuteAssignType() {
        return chuteAssignType;
    }

    /**
     * Sets the value of the chuteAssignType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setChuteAssignType(JAXBElement<String> value) {
        this.chuteAssignType = value;
    }

    /**
     * Gets the value of the itemBreakAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getItemBreakAttribute() {
        return itemBreakAttribute;
    }

    /**
     * Sets the value of the itemBreakAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setItemBreakAttribute(JAXBElement<String> value) {
        this.itemBreakAttribute = value;
    }

    /**
     * Gets the value of the inventoryAllocationType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInventoryAllocationType() {
        return inventoryAllocationType;
    }

    /**
     * Sets the value of the inventoryAllocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInventoryAllocationType(JAXBElement<String> value) {
        this.inventoryAllocationType = value;
    }

    /**
     * Gets the value of the pickupReferenceNbr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPickupReferenceNbr() {
        return pickupReferenceNbr;
    }

    /**
     * Sets the value of the pickupReferenceNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPickupReferenceNbr(JAXBElement<String> value) {
        this.pickupReferenceNbr = value;
    }

    /**
     * Gets the value of the deliveryReferenceNbr property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeliveryReferenceNbr() {
        return deliveryReferenceNbr;
    }

    /**
     * Sets the value of the deliveryReferenceNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDeliveryReferenceNbr(JAXBElement<String> value) {
        this.deliveryReferenceNbr = value;
    }

    /**
     * Gets the value of the lineRefTextField1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField1() {
        return lineRefTextField1;
    }

    /**
     * Sets the value of the lineRefTextField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField1(JAXBElement<String> value) {
        this.lineRefTextField1 = value;
    }

    /**
     * Gets the value of the lineRefTextField2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField2() {
        return lineRefTextField2;
    }

    /**
     * Sets the value of the lineRefTextField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField2(JAXBElement<String> value) {
        this.lineRefTextField2 = value;
    }

    /**
     * Gets the value of the lineRefTextField3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField3() {
        return lineRefTextField3;
    }

    /**
     * Sets the value of the lineRefTextField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField3(JAXBElement<String> value) {
        this.lineRefTextField3 = value;
    }

    /**
     * Gets the value of the lineRefTextField4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField4() {
        return lineRefTextField4;
    }

    /**
     * Sets the value of the lineRefTextField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField4(JAXBElement<String> value) {
        this.lineRefTextField4 = value;
    }

    /**
     * Gets the value of the lineRefTextField5 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField5() {
        return lineRefTextField5;
    }

    /**
     * Sets the value of the lineRefTextField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField5(JAXBElement<String> value) {
        this.lineRefTextField5 = value;
    }

    /**
     * Gets the value of the lineRefTextField6 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField6() {
        return lineRefTextField6;
    }

    /**
     * Sets the value of the lineRefTextField6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField6(JAXBElement<String> value) {
        this.lineRefTextField6 = value;
    }

    /**
     * Gets the value of the lineRefTextField7 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField7() {
        return lineRefTextField7;
    }

    /**
     * Sets the value of the lineRefTextField7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField7(JAXBElement<String> value) {
        this.lineRefTextField7 = value;
    }

    /**
     * Gets the value of the lineRefTextField8 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField8() {
        return lineRefTextField8;
    }

    /**
     * Sets the value of the lineRefTextField8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField8(JAXBElement<String> value) {
        this.lineRefTextField8 = value;
    }

    /**
     * Gets the value of the lineRefTextField9 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField9() {
        return lineRefTextField9;
    }

    /**
     * Sets the value of the lineRefTextField9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField9(JAXBElement<String> value) {
        this.lineRefTextField9 = value;
    }

    /**
     * Gets the value of the lineRefTextField10 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField10() {
        return lineRefTextField10;
    }

    /**
     * Sets the value of the lineRefTextField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField10(JAXBElement<String> value) {
        this.lineRefTextField10 = value;
    }

    /**
     * Gets the value of the lineRefNumberField1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField1() {
        return lineRefNumberField1;
    }

    /**
     * Sets the value of the lineRefNumberField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField1(JAXBElement<String> value) {
        this.lineRefNumberField1 = value;
    }

    /**
     * Gets the value of the lineRefNumberField2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField2() {
        return lineRefNumberField2;
    }

    /**
     * Sets the value of the lineRefNumberField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField2(JAXBElement<String> value) {
        this.lineRefNumberField2 = value;
    }

    /**
     * Gets the value of the lineRefNumberField3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField3() {
        return lineRefNumberField3;
    }

    /**
     * Sets the value of the lineRefNumberField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField3(JAXBElement<String> value) {
        this.lineRefNumberField3 = value;
    }

    /**
     * Gets the value of the lineRefNumberField4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField4() {
        return lineRefNumberField4;
    }

    /**
     * Sets the value of the lineRefNumberField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField4(JAXBElement<String> value) {
        this.lineRefNumberField4 = value;
    }

    /**
     * Gets the value of the lineRefNumberField5 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField5() {
        return lineRefNumberField5;
    }

    /**
     * Sets the value of the lineRefNumberField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField5(JAXBElement<String> value) {
        this.lineRefNumberField5 = value;
    }

}
